### ISSUE TITLE
Reloading app no loinger alows comparison to saved runs

### ISSUE THREAD

**Issue by StephanSchaller** [esqLABS/TissueTMDD#53]
I saved a run, it was then available for comparison. then I hit F5, and I could no longer select the old run for comparison.
Maybe we can add "browse" to select the saved JSON (after all it is in your download folder)?

**Comment by Felixmil** [comment]
Once you exported the setting to JSON, you can reimport it afterward using the Import section:
![image](https://github.com/user-attachments/assets/5942ac89-65cb-4fb3-a8b9-2d1299fd9834)

However, simulation results are not part of the saved settings so you'll have to rerun it.
